### ISSUE TITLE
关于最近美团的问题

### ISSUE THREAD

**Issue by chemist0086** [shengxinjing/programmer-job-blacklist#102]
详见https://zhuanlan.zhihu.com/p/27989039

主要是清真食品分箱，招聘使用"黄泛区"等歧视词，物化女性等，让人严重怀疑其公司的价值观和企业文化

**Comment by AngryLi** [comment]
如果把这些都反过来，是不是还有这么多反对者。

**Comment by tcitry** [comment]
而且美团的处理方式都是和犯错误的人划清界限。

**Comment by Mrchangchang** [comment]
饿了么：不是我做的有多好，都靠同行衬托的啊~~

**Comment by LittleStupid** [comment]
美团这个是公关的锅吧

**Comment by chemist0086** [comment]
说是公关的锅我不同意，公关做的好不代表这些事情就不存在，相反的，公关将事态进一步扩大化更加说明了这家公司的价值观存在问题。

**Comment by Songyu-github** [comment]
价值观不同，从根上就是这样的

**Comment by shengxinjing** [comment]
清真话题太敏感 关了吧
