### ISSUE TITLE
南京碎片工坊网络科技有限公司——来自知乎

### ISSUE THREAD

**Issue by lsytj0413** [shengxinjing/programmer-job-blacklist#104]
具体内容见链接:

[流年不利进坑奇葩公司，遇小人，提醒南京攻城狮门，巨坑！！【南京碎片工坊网络科技有限公司】](https://zhuanlan.zhihu.com/p/28169143)

**Comment by scofieldpeng** [comment]
@lsytj0413 知乎404 not found,建议直接贴到这里

**Comment by shengxinjing** [comment]
404 closed
