### ISSUE TITLE
广州奔步电脑

### ISSUE THREAD

**Issue by gxrsprite** [shengxinjing/programmer-job-blacklist#124]
这个外包公司某月拿了我工作所在公司的钱后砍了上海分部，无故说我们违纪，然后工资不发赔偿不发仲裁后一直拖，工作地方都给钱给奔步了，反过来不服仲裁法院起诉，还用要上刑事为借口继续拖延。

**Comment by gxrsprite** [comment]
![qq 20180404100331](https://user-images.githubusercontent.com/6988665/38284889-259792f8-37f0-11e8-9510-78469a945b30.png)
案件目前还无进展，审判法官听信对方说我的严重违纪，对方要上刑事但其实毫无进展，因为没有能上刑事的事情，就是拖时间，到现在还没拿到赔偿

**Comment by shengxinjing** [comment]
求知乎连接之类的东东

**Comment by gxrsprite** [comment]
@shengxinjing
