### ISSUE TITLE
怎么能少得了我大百度呢？

### ISSUE THREAD

**Issue by medmin** [shengxinjing/programmer-job-blacklist#13]
厂商：百度
原因：太多了

**Comment by shengxinjing** [comment]
求连接

**Comment by medmin** [comment]
https://www.zhihu.com/question/29740126
https://www.zhihu.com/question/30692508
百度直接坑程序员的事还真的一时半会儿没找到，但是剩下的全是黑点

**Comment by ChenCody** [comment]
这位同学请注意审题.......这个是项目是收集公司直接坑员工的事例，你发的两个链接都跟这个没关系，百度坑用户的事例发发知乎就好了，坑员工的发这里。

**Comment by shengxinjing** [comment]
@medmin 我只收集坑员工和坑合伙人的

**Comment by pi1ot** [comment]
我刚才提交的蔡文胜坑曹政的案例怎么没有收录？

**Comment by pi1ot** [comment]
@shengxinjing 我刚才提交的蔡文胜坑曹政的案例怎么没有收录？

**Comment by wizardforcel** [comment]
不收录坑用户的公司。况且你又不提供具体事件。

**Comment by zhanglun** [comment]
百度医疗部门。。不知算不算额。。

**Comment by pi1ot** [comment]
@zhanglun 我感觉是算的

**Comment by shengxinjing** [comment]
@zhanglun 算啊 加上

**Comment by shengxinjing** [comment]
@zhanglun 我仔细看了下医疗事件，允许转岗，裁员也有赔偿 我觉得还行吧

**Comment by shengxinjing** [comment]
@pi1ot 有链接吗？我看看

**Comment by pi1ot** [comment]
蔡文胜与曹政股权
https://www.zhihu.com/question/23552172
https://www.zhihu.com/question/23554339
@shengxinjing

**Comment by shengxinjing** [comment]
@pi1ot merged
