### ISSUE TITLE
良友佳医智慧医疗科技（北京）有限公司

### ISSUE THREAD

**Issue by songwenju** [shengxinjing/programmer-job-blacklist#136]
法人任晨光，qq：372397206，电话：15311196265.公司刚刚成立两个月忽悠说有好几个分部。忽悠能力强，骗走源码后，一直拖着不结尾款。此人正在做一个医疗相关的盒子项目。据了解目前有三个人被骗，被骗金额高达16000元左右。（和当事人确定了具体金额后修改，其余二人均称此人欠钱，并多次要没有给，由于没有合同，故拉黑了此人）。

**Comment by CIACloud** [comment]
下周带着你的破代码去你们公司找你,给你们领导看看 你他们骗我一台电视两个盒子

**Comment by CIACloud** [comment]
你他妈一拖再拖, 就剩四天时间了突然说你要参加培训不做了?项目烂尾关你屁事? 你一大男人还要脸不了

**Comment by CIACloud** [comment]
给大家解释下这三个圈内人 一个来签约后第二天家里有事回老家了, 第二个从始至终就写了一个静态页面还bug一堆, 第三个就是找他俩来的你宋文举吧 我不针对他俩, 合约是你签的 超出二十多天我说啥了 加钱让你们继续往下做, 你说你要去培训不干了 项目烂不烂尾不关你事 我说宋文举 你要是男人的话正面回复下, 你现在怎么连我电话都不敢接,你心虚不

**Comment by CIACloud** [comment]
要不是你这条狗到处乱喷 我都没空搭理你 ,为什么不说你临时撂挑子我现找人去做 费用上我要多花很多, 湖北那个我扣他一千尾款付了九千 ,因为bug一堆 他又没空修,做视频列表没有上拉加载这种你觉得像话吗? 北京姓李的他敢说我没全付给他吗? 把他叫出来

**Comment by CIACloud** [comment]
在你撂挑子之后找来的两人 虽然没有签合约 但是已按口头协议支付合理报酬, 武汉的蒋同学因遗留bug太多且无意愿继续修复 ,原定一万 实付九千. 北京李同学全额支付, 付款记录尚在, 必要时可申请法院取证. 你最好别删以上内容, 因为你这诽谤行为算是坐实了 另外二手电视及两台全新的盒子(499一台) 再不值钱也超出诈骗标准了

**Comment by CIACloud** [comment]
宋文举 为什么别人没合约的都能拿到报酬而你签和合约又签了保密协议 还要沦落至此, 你真应该好好想想了,  合约本就防小人不防君子, 你以为签了合约 再敷衍几天就可以如约拿到钱吗? 周一到周五你说你上班没空弄,周六日你说你陪女朋友 你摸着良心想想你总共写了几行代码????

**Comment by CIACloud** [comment]
你肆意捏造事实,散播谣言,当真可以为所欲为吗? 你忘了你签了保密协议了吗???? 就凭这个你就输定了

**Comment by CIACloud** [comment]
你洋洋洒洒写了几千字 能证明啥? 你受骗了? 所骗何物? 拿出来看看...

**Comment by CIACloud** [comment]
清者自清 这词儿你也敢用?? 你一个受害人还怕我在你的博文下回帖举证一下吗? 看你删帖的速度不愧是惯用右手. 我才刚发你就删了?? 姑且问你一句 你说你掏不起一万起诉费, 我要起诉你问你要地址的时候你为何说: 你等着吧 等我寄给你就行了. 我等了一个多月才发现 你跑网上乱吠来了 你的律师哪去了?

**Comment by songwenju** [comment]
说好项目分期结，你一期拖着不给，会给你做二期？你摸着你的良心说，我给你拖二十天？是你12号演示的版本没有做好，还是你后来加的需求没有给你做完，你合同上做鬼就算了，后来你定的周一晚上写完新需求，我给写完发给你，你回都不回。然后说我们有一个体验性的bug，一直拖着不给结啊，bug解了也没有见你结啊。我不给你加钱，给你做好，你还好意思说出来。他们两个我已经确认了，你拖欠了他们的尾款，要我给你看截图吗？为何三个不认识的人和你合作之后都把你拉黑了，你这种过河拆桥的人，在我的文章后面瞎逼逼。按照他们的话说：这种烂人 就不要理他了！！！

**Comment by CIACloud** [comment]
别人没合同也能拿到钱，谁说我没给他，你最好有证据指出来，否则别胡说八道

**Comment by CIACloud** [comment]
北京的李同学跟你说我欠他钱了吗？你敢拿人格担保吗？如果他真这么说过，我连你俩一起告，如果没有，我俩一起告你！！！

**Comment by CIACloud** [comment]
你们工作没有在约定时间内按要求做完，我为什么要按约定给你付款啊？这么好骗啊？？？ 你最好找个律师去赶紧，别在这儿丢人现眼了

**Comment by CIACloud** [comment]
骗不到钱就到网上散播谣言，你以为我会妥协？？？做梦吧你，这事儿你输定了

**Comment by CIACloud** [comment]
自己几斤几两重你不清楚吗？跟我玩儿什么泼皮无赖的把戏，你有这功夫不如踏踏实实做事，少给人弄几个烂尾项目然后拍拍屁股走人。你恶不恶心啊你

**Comment by CIACloud** [comment]
你拿别人项目当儿戏随便糊弄应付一下就想赚钱？你咋不躺着赚钱呢或许来的更快些，骗人这条路以你的智商走不通的你知道不

**Comment by CIACloud** [comment]
https://www.jianshu.com/p/f376231317f2

**Comment by CIACloud** [comment]
按完成度和质量付费 这是行规 湖北武汉姓蒋的那位 虽然没有合约 你开价一万 我付你九千, 其中原因你心里没点儿数吗? 李士民你开价6000 付了你6000, 最终达成协议由你修复自己及蒋同学遗留的bug 再额外付费 问题是你改了吗????? 我bug还没整理好给你你就消失了 现在搁这儿凑什么热闹 宋文举你签了合约又毁约, 你还有脸要钱吗????

**Comment by songwenju** [comment]
湖北蒋同学原话（有截图）：
他随意加新需求，然后说我没完成咯？！！ 
还反咬一口，这人真恶心 
然后验了一个星期也没时间，我就拉黑他了
辛亏第二笔款的时候，我咬死不给款，就不发源码
不然就亏大发了
1.之前讨论好的需求中并没有这条  2.一个列表就一个测试数据，做他妈的翻页 3.实际情况是他拖着不测试，简单来说就是赖账

**Comment by CIACloud** [comment]
你发这两条你自己觉得搞笑不，你亏不亏心

**Comment by CIACloud** [comment]
你们这些下三滥招数还好意思说，总之一句话，他俩做事可以拿钱，你不做没有！姓蒋的没就挖那么多坑，姓李的为什么要来赚填坑的钱。问题是他做了吗？摸着良心想想！

**Comment by songwenju** [comment]
首先给你做这个项目，不是想挣你钱的，也不差你这些钱，创业不易，当时只是想帮一个创业者。其次，不要拿我对象说事，每个人都有评判权，我没有让她参与进来，懂吗？此贴我不再回，浪费时间，交给后来人自己评判。

**Comment by CIACloud** [comment]
首先这事儿跟她没关系，让她安份些！你这么高尚，我需要临时找人？你再嘴巧也抵不过我付他俩一万五扣一千的事实。姓蒋的约定的工作都偷工减料还指望他做新加的，你发这个你亏心不！！
