### ISSUE TITLE
十堰格亚文化传媒有限公司

### ISSUE THREAD

**Issue by jiafulu** [shengxinjing/programmer-job-blacklist#139]
法人： 谢天琦
电话：15927547464.
公司于5月20号搬至广州市荔湾区立白大厦对面栗子谷孵化中心三楼，拖延工资是常事，
离职人员目测拖工资更久，离职第19天了，谈好的15号，然而已过了三天，询问结果是月底，周六去找他协商，
未完待续
2018/7/18

**Comment by Wanxp** [comment]
这种公司十有八九是拖很久都不会给

**Comment by jiafulu** [comment]
结局： 拖延将近两个月才要到了工资

**Comment by jiafulu** [comment]
另外提醒下兄弟们去这家一定慎重考虑，
毕竟老板不仅仅是在口头上说了项目做完了还要技术干啥用，
实际行动也做了，项目5月20开始，现在是8月22，技术部在几天前解散，一个没剩下。
