### ISSUE TITLE
希望维护程序员的利益的同时，尊重一下事实

### ISSUE THREAD

**Issue by powerkom** [shengxinjing/programmer-job-blacklist#142]
这个名单初衷是好，但是劳动者和企业其实在今日科技界，劳动者的不职业一样会给企业带来巨大的损失。难道就因为劳动者是相对弱势的一方就能证明他们所说的都是正确的吗？没有事实依据，只是一面之辞就让这些不负责责任的言论在网络上流传吗？这个所谓的黑名单一点都起不到作用！希望不要被人利用了！

**Comment by shengxinjing** [comment]
好的:smile:
