### ISSUE TITLE
浙江竹开信息科技有限公司

### ISSUE THREAD

**Issue by FromThePast** [shengxinjing/programmer-job-blacklist#145]
以下是我的经历
1，17年下半年平均每月加班50-60小时，没有调休和加班补贴什么的。老总当着所有技术的面开会，承诺年底多发一个月奖励，后来快过年了绝口不提这件事， 找了个小借口（是HR出来说口头承诺不算，必须发邮件，老总也不行，）把这个是糊弄过去了，耍赖了。
2，之前的餐补（10元/天）， 后来取消了。
4，年终奖不在年终发，变年中发，4月15一拖再拖到4月底，5月初才发， 那时我已离职， 而且发的很乱，按照基础工资的入职月数发， 基础工资后来强行调到3k。
5，听说之前劳资纠纷挺多，有好几个合作的架构师，因为不分红去劳动局闹过。
8， x月中旬涨的薪水，要到(x + 2)月1号才开始算，但是餐补x月就没了， 参考第二条。
9，活多的时候招人，招进来干了之后，没活了开始开人，没有赔偿的，说什么末尾淘汰制，无论你干的好坏。
10，17年会火星工场自己玩一天，晚饭也是里面吃的，桌子是拼的，吃到一半酒没了，还是临时去买的。
11，节假日基本没福利，中秋节最廉价的月饼都不发，也没其余福利的。
12，我认识的同事基本离职了。
13，本月离职，上一个月干满的情况下，绩效归0。 基本工资发的很少，相当于你干半个月， 拿到手1000块
14，公司的管理制度是管理层可以不动， 但是底下的员工随便离职没关系的，16 年 17年都是，几个销售关系好的， 财务和行政都是老板的亲戚，每年换一批开发。
15，开发的技术都很一般的， 都是刚培训完，或者刚毕业的。别问我为什么去那里， 有个朋友当组长叫我去的，不过早就一起离职了。
16， 工资压的很低，好几个来了入职一天就走了。
17， 单双休制度
18，杭州境内出差，都是员工开车带其他员工， 6点多起来，开车2小时， 然后下班10点多，或者12点，再回去， 你想想就知道了。
19，往公司投了10万的员工， 年底没分到红， 但是公司是肯定赚钱的， 两个老总一个买了Q5， 一个买了5系。 真的扣的不行，朝令夕改的。 每一句实话。
20， 有点什么决定就董事会，董事会， 哪有什么董事会。都是他们自己做主的。

总结，反正我离职后对这家公司意见是很大的， 经常性的加班到凌晨，甚至通宵也不少。但是没有其他补贴你的。 吐槽不完的， 公司我也待过几家，我没见过这样的公司， 是真的恶心到我。

**Comment by shengxinjing** [comment]
求知乎连接之类的
