### ISSUE TITLE
上海源涞实业

### ISSUE THREAD

**Issue by mrdulin** [shengxinjing/programmer-job-blacklist#157]
![qq 20160512173135](https://user-images.githubusercontent.com/17866683/46572261-5f4dd500-c9b5-11e8-9eb4-416fd2910838.png)
![qq 20160512173209](https://user-images.githubusercontent.com/17866683/46572262-61b02f00-c9b5-11e8-9fc0-c7af073c80a2.png)

**Comment by zqq90** [comment]
@mrdulin  
谁要是一天一条，我准屏蔽他
