### ISSUE TITLE
希望加上房产中介，还有哪些装逼的人力资源。

### ISSUE THREAD

**Issue by daxia4444** [shengxinjing/programmer-job-blacklist#19]
我可以创建一个web站点来专门显示这些无人品人事么？

**Comment by daxia4444** [comment]
感觉资源还是少了一点，可以用机器学分类，然后数据手机多一点！

**Comment by shengxinjing** [comment]
额 这个我倒是想加，但是没有啥确信资源啊

**Comment by wqw547243068** [comment]
黑中介一大堆，不少跟黑社会有染

**Comment by medmin** [comment]
不要建网站吧，容易被黑被攻击。github挺好。只要只搜集网络信息和新闻，那就很安全。厂商公关出马也删不掉repo
