### ISSUE TITLE
我不服，我不服，我不服

### ISSUE THREAD

**Issue by TutorSBC** [shengxinjing/programmer-job-blacklist#191]
我TutorABC，裁员30%，不愿意赔偿，美名其曰对你培训，让你签订绩（qu）效（ta）考（ma）核（bi）计划），hr轮番轰炸，挨个聊天，让你签订，不愿意签订就默认同意。人事小姐姐那一副美丽的嘴脸，亲爱的，亲爱的叫真是令人叫呕

**Comment by shengxinjing** [comment]
求证据链接呀
