### ISSUE TITLE
支持，绝对支持

### ISSUE THREAD

**Issue by c4dr01d** [shengxinjing/programmer-job-blacklist#193]
这个黑名单必须支持，真的找工作要看公司，不看公司的话，吃亏的永远都是我们程序员自己

**Comment by MarcSteven** [comment]
是的，现在开公司太容易了，所以很多皮包公司

**Comment by c4dr01d** [comment]
没办法，要对这些公司有所防备

**Comment by MarcSteven** [comment]
这和国外不一样，国外很多是技术驱动型公司不单纯靠融资养活公司，都有造血功能，很多公司都50人以下但是都活得还不错

**Comment by c4dr01d** [comment]
国外完全和国内两回事

**Comment by MarcSteven** [comment]
国内程序员都是苦逼出身
