### ISSUE TITLE
关于软通动力-北京

### ISSUE THREAD

**Issue by adminlinzi** [shengxinjing/programmer-job-blacklist#204]
在脉脉上实名区看到了软通动力的补助和报销出现异常
原文地址：https://maimai.cn/web/feed_detail?fid=1075048070&efid=uVP0S9-lXFFGjSvdEWC87w
![default](https://user-images.githubusercontent.com/6985067/52269431-013bf900-2979-11e9-9575-50311de5ab33.png)

**Comment by hanbin** [comment]
目前就职软通，公司人太多，软通目前年会都是每个产品线自己搞了。
年终奖据说满一年有，但是估计和平时的绩效以及和老板的关系都有密切关系。
没有出过差。

**Comment by adminlinzi** [comment]
> 
> 
> 目前就职软通，公司人太多，软通目前年会都是每个产品线自己搞了。
> 年终奖据说满一年有，但是估计和平时的绩效以及和老板的关系都有密切关系。
> 没有出过差。

出现这种实名动态，对公司继续招聘还是有不太好的影响的

**Comment by huangjj27** [comment]
> 出现这种实名动态，对公司继续招聘还是有不太好的影响的
这样才能优胜劣汰. 理想的公司应该是拼效率, 而不是拼时间, 然而目前, 许多公司为了产出而压榨员工, 这对**企业和员工的发展都没有好处**

请那些把企业当成是个人**违规, 违法赚快钱的工具**的老板们, 三思您们以后的领导生涯!

**Comment by huangjj27** [comment]
> 年终奖据说满一年有，但是估计和平时的绩效以及和老板的关系都有密切关系

诶 这样子的吗? 我第一次听说, 目前离满一年还有一段时间.

**Comment by hanbin** [comment]
> > 年终奖据说满一年有，但是估计和平时的绩效以及和老板的关系都有密切关系
> 
> 诶 这样子的吗? 我第一次听说有年终奖, 目前离满一年还有一段时间. 坐标广州
我坐标深圳，我这边还好。另外，在这种外包性质的公司，个人对项目的价值尤其重要。

**Comment by huangjj27** [comment]
> 我坐标深圳，我这边还好。另外，在这种外包性质的公司，个人对项目的价值尤其重要。

客户不在乎这些，客户只要能够做完了交出去，之后的锅全让你背，包括客户前期负责的客户内部沟通与设计导致的延误。也就是，都做好了才说需求不对， 让你加班改。你还能怎么办
