### ISSUE TITLE
出面维护有赞996的一些舔狗需要建立黑名单吗？

### ISSUE THREAD

**Issue by Mishidexfc** [shengxinjing/programmer-job-blacklist#208]
刚在脉脉上看到上海某公司的总监发脉脉力挺996

**Comment by shengxinjing** [comment]
没法实名制 没法加呀

**Comment by bwangelme** [comment]
我认为这个名单的目的应该是记录一些已经发生的事实，在程序员在找工作时为他们提供一个参考。

如果因为某些人发表过某种言论，就维护个黑名单，把他们挂起来。这样的做法欠妥。这就像过去搞得划分黑五类一样，因为你之前发表过某种言论，就是程序员的公敌，就要被程序员群体踏上一万只脚踩得永世不能翻身。

**Comment by Mishidexfc** [comment]
> 我认为这个名单的目的应该是记录一些已经发生的事实，在程序员在找工作时为他们提供一个参考。
> 
> 如果因为某些人发表过某种言论，就维护个黑名单，把他们挂起来。这样的做法欠妥。这就像过去搞得划分黑五类一样，因为你之前发表过某种言论，就是程序员的公敌，就要被程序员群体踏上一万只脚踩得永世不能翻身。

能理解，但不完全赞同。公司的一些决策最终还是某个人或者是某群人的意志，有赞996毕竟还是高层或者说白了是有赞CEO决定的，和有赞的基层员工没什么关系。
那换个思路，如果有赞CEO开了家新公司，然后求职的朋友没能了解到有赞CEO是谁，那不仍然有高风险遇到坑吗？
我不是说一定要对某些人永远不能翻身，但做过的事情说过的话毕竟是已经公开的，这个列表应该是维护一些互联网圈子里“发生过的事情”，只不过有些人的言论和某些公司发生的大事紧密相关罢了。就比如有赞996事件，能绕开有赞CEO这个人的言论吗？
