### ISSUE TITLE
如何评价阿里 HR 对离职员工谈话造假

### ISSUE THREAD

**Issue by pinkelf** [shengxinjing/programmer-job-blacklist#21]
https://www.zhihu.com/question/30328482

**Comment by vczh** [comment]
@shengxinjing 这个没有贴上去吗？

**Comment by shengxinjing** [comment]
@vczh 感觉这个是阿里HR的问题，和月饼那个算是重复了吧 囧

**Comment by vczh** [comment]
@shengxinjing 没关系，链接可以加。
