### ISSUE TITLE
建议增加上榜时间

### ISSUE THREAD

**Issue by libook** [shengxinjing/programmer-job-blacklist#214]
建议增加上榜时间，因为随着时间的变化，企业内部情况也可能会有所变化，增加上榜时间能保住大家了解到企业出现问题的时期，辅助更客观评估企业现状。
毕竟有心吸取教训改革自新的企业还是应该获得被大家关注的机会的。

**Comment by shengxinjing** [comment]
赞 没问题 正在做结构化数据
