### ISSUE TITLE
黑历史大集合么，资料多了后加上地域性的分类

### ISSUE THREAD

**Issue by martint028** [shengxinjing/programmer-job-blacklist#22]

**Comment by shengxinjing** [comment]
现在资料太少 多了后可以考虑

**Comment by martint028** [comment]
@shengxinjing 
![](https://cloud.githubusercontent.com/assets/12568845/23249173/ef66128c-f9dd-11e6-9e58-ad23096dfecb.png)
上了GitHub Trending页了，star点起来

**Comment by shengxinjing** [comment]
@martint028 太屌了 赞
