### ISSUE TITLE
连star的人我也佩服，你们找工作的岗位都是技术合伙人。

### ISSUE THREAD

**Issue by lacklock** [shengxinjing/programmer-job-blacklist#23]
找的岗位不是技术合伙人就是创始人，需要这样一份名单。

我们程序员光是活着就很辛苦了。公司老板人品和我搬个砖能有什么关系。

多给我5k，写php都行。

**Comment by medmin** [comment]
又黑我大PHP

**Comment by pi1ot** [comment]
你的意见不矛盾，也许多年以后你也有机会用上，仅作为参考，“互联网不会忘记”

**Comment by shardings** [comment]
弄个黑名单怎么了。难道还不让人说这些话题了？
不行多建个账号然后匿名呗。
github现在都快成实名的了，实名的github多无趣，简历可以去linkedin啊。正好匿名了多做点有意思的事儿。

传送门：如何多个github号用多个sshkey， https://gist.github.com/jexchan/2351996

**Comment by zohoFrank** [comment]
不太懂lz的逻辑，合着所有人都得像你一样，安心搬砖就对了？劳动者权利被哪种人拖得后腿，你猜猜？

**Comment by lacklock** [comment]
我讲个笑话，作者是百度的。

**Comment by samhou1988** [comment]
又中枪了

**Comment by shardings** [comment]
@lacklock  大道废，有仁义。智慧出，有大伪。六亲不和，有孝慈。国家昏乱，有忠臣。

**Comment by shengxinjing** [comment]
@lacklock 我已经不在百度两年多了，现在就是在创业
