### ISSUE TITLE
360企业安全

### ISSUE THREAD

**Issue by CharleyXu** [shengxinjing/programmer-job-blacklist#261]
1.公司制度不透明，年终临近发之前都不知道什么时候发。纱布领导还故意打低的绩效系数来糟践你，关键进来的时候HR还拿总包压低你薪水

2.混乱，流程混乱。工期领导拍脑袋定，部门一点凝聚力都没有

3.加班多，领导不报批不给调休

4.根本学不到东西，做技术的来说就是浪费时间

5.360企业安全和360集团就是两个实体，关系呢企业安全在酒仙桥占了人家的几层工位

**Comment by qq2556951268** [comment]
360企业安全有这么差？

**Comment by CharleyXu** [comment]
> 360企业安全有这么差？

脉脉搜一下就是了，拿总包压社招，拿奇虎牌子骗应届生。我们主管对绩效还给上人生一课，没见过那么糟贱人的，忍到离职之后我会还回来

**Comment by leisurelicht** [comment]
> 360企业安全有这么差？

所有项目无延期按时完成，一个人负责多个项目的设计，开发，部署，运维。绩效的评价是符合预期，产出不足。我都不明白产出不足是怎么符合预期的。就是为了压你年终。
