### ISSUE TITLE
搜狗王小川实名骂人

### ISSUE THREAD

**Issue by xbhoneybee** [shengxinjing/programmer-job-blacklist#262]
![image](https://user-images.githubusercontent.com/18543388/55600765-2a69e180-5790-11e9-81ac-ab045f8c2645.png)

**Comment by xiaomoqianhei** [comment]
搜狗怎么还没凉…

**Comment by molixiu** [comment]
> 
> 
> 搜狗怎么还没凉…
搜狗有输入法，现在还是老大

**Comment by molixiu** [comment]
兄弟，你现在很危险呐

**Comment by meitiever** [comment]
名起的不对，骂人都算轻的了。
把问题放在重点上。

**Comment by ss7247** [comment]
有什么用呢？要么反抗，要么接受
