### ISSUE TITLE
是否可以归档保存链接原网页（或截图）？

### ISSUE THREAD

**Issue by croath** [shengxinjing/programmer-job-blacklist#29]
防止原文被删

**Comment by shengxinjing** [comment]
知乎太长了，不好截图吧，还是直接放链接吧

**Comment by lilydjwg** [comment]
可以用 Internet Archive 的。如果是微信文章，因为 robots.txt 的禁止，只能用 Archive.is。

**Comment by NeverBehave** [comment]
建议将网页保存下来放在repo，如果样式不方便可以转成.md方便展示。知乎那些说删就删了真的不保险

**Comment by flyerSon** [comment]
这个建议不错！
