### ISSUE TITLE
西安归毂智能科技成都公司

### ISSUE THREAD

**Issue by painoBoy** [shengxinjing/programmer-job-blacklist#303]
老板让每个员工电脑装monitor监控软件,每天监控着员工电脑，连键盘每天的按键次数都监视到，地址在环球中心,这种老板留着干什么啊

**Comment by qiywtc** [comment]
竟然有这么棒的老板……

**Comment by qiywtc** [comment]
> 老板让每个员工电脑装monitor监控软件,每天监控着员工电脑，连键盘每天的按键次数都监视到，地址在环球中心,这种老板留着干什么啊

竟然有这么棒的老板……

**Comment by qmsggg37** [comment]
厉害的很
