### ISSUE TITLE
-

### ISSUE THREAD

**Issue by gdhcrl** [shengxinjing/programmer-job-blacklist#309]
-

**Comment by MonsterRob** [comment]
日了

**Comment by LiHaiyuan** [comment]
举报就举报，人身攻击毫无必要，还会降低可信度

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: gdhcrl <notifications@github.com>
发送时间: Tuesday, July 30, 2019 10:50:10 PM
收件人: shengxinjing/programmer-job-blacklist <programmer-job-blacklist@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [shengxinjing/programmer-job-blacklist] 广东汇才人力资源有限公司 拖欠工资 (#309)


广东汇才人力资源有限公司, 一年前曾在这家公司工作过, 细数一下这家公司的坑.

  1.  不签订劳动合同, 给员工签订劳务协议, 也就是说员工不受劳动法保护, 要是有什么争议的话就只能直接去法院起诉, 唉, 可怜的员工哪里有时间更这种公司打官司啊.
  2.  公司没有五险一金, 因为没有签订劳动合同, 所以你去社保局、公积金管理处投诉也没有用. 要想维权, 就只能先去劳动监察大队申请仲裁成为劳动关系.
  3.  还有一个坑钱规定:公司规定入职或离职当月上班不满月的，当月工资按实际出勤天数计算. 意思就是说你就只能在每个月的1号入职和提起离职, 不然就扣你节假日的工资. 面试、入职都不会跟你讲的, 就是忽悠你进来就行了.
  4.  这家公司是搞人力资源外包的, 所以经常有招聘会. 公司领导为了省钱就会让自己的员工去搬桌子、搬椅子、搭帐篷, 如果你是男的就更惨了, 而且经常是要加班到晚上2、3点. 调休倒是有, 不过给你调休个4小时, 你觉得划算吗? 而且同样面试、入职都不会跟你讲的.

一般通知你面试的都是一个女的, 原名就郭晓燕, 40多岁的老太婆, 她一般会称自己为陈小姐、蔡小姐, 估计就是怕被人报复就把自己的姓氏给改了. 她的微信号是hanyuma, 手机号码: 18923988335, 看到这个号码一定要录音, 这个臭婊子口头说的都不能信.

[image]<https://user-images.githubusercontent.com/53470873/62139616-40417a80-b31c-11e9-9076-aac41c3fca7e.png>
这就是郭晓燕, 臭婊子

―
