### ISSUE TITLE
艾漫 基础工资2.5k/月，工作5年才4.5k/月，极低

### ISSUE THREAD

**Issue by SPRCSY** [shengxinjing/programmer-job-blacklist#312]
非程序员岗
上海地区工作5年的淘宝负责人才4. 5k/月
KPI过高完成不了：实质没有提成

薪资水平过低，虽然产品很贵，利润大部分被老板吃掉了

**Comment by rootexplorer** [comment]
那还和他玩什么？

**Comment by vczh** [comment]
感觉这不能成为上blacklist的理由，人家早就说好了就这么点钱了，没有试图骗人。
