### ISSUE TITLE
不管您有多少牢骚, 有多少委屈需要维权或安慰, 请不要通过Github来做

### ISSUE THREAD

**Issue by xixilive** [shengxinjing/programmer-job-blacklist#34]
我并不是要评论"库主"的观点/想法/动机, 
只想说 Github是一个纯净的技术社区, 
引入这些非技术的自由内容,可能引起某些方面的注意, 到时候又要请李老师来呼吁不要墙Github吗?
希望所有的开发者来维护这份纯净,
也希望Github可以介入处理这类Repo

**Comment by shengxinjing** [comment]
被坑这么惨，还不是技术内容，不懂啊，不喜欢的话ctrl+w就可以啦

**Comment by shengxinjing** [comment]
@xixilive 还有，你的论点很奇怪，难道墙github是因为我吗？那我如果只用google搜技术问题，只用youtube看动画片，难道墙就会取消？

**Comment by martint028** [comment]
naive

**Comment by canghai118** [comment]
我是觉得不要再这边有过多的讨论和口水。
本来点了watch，结果被邮件轰炸了，现在unwanted了。

**Comment by vczh** [comment]
@canghai118 你可以简单的关掉notification发送邮件的功能的，我觉得看那些邮件也没有用，里面就一个链接。

**Comment by coderev** [comment]
你不要watching不就完了，只要GitHub没管，有什么理由要关掉
留给其他人做个参考，同时也给SB公司一点教训有什么不好

**Comment by ShootToThrill** [comment]
太逗了你
你整天忙着钻技术，别人整体忙着研究怎么 宰你
了解些这些东西是很有必要的
另外我很怀疑你的动机

而且 就算被墙了又怎样
翻墙是基本功好吗
翻墙都不会还谈技术？
