### ISSUE TITLE
能链集团（车主邦）

### ISSUE THREAD

**Issue by wqmeepo** [shengxinjing/programmer-job-blacklist#344]
帮一社招进去的朋友提交的
1、关于加班：入职前HR说公司不提倡加班，入职后隐形996，不996会被ceo带头优化（有领导群CEO的聊天截图作证）。
2、关于转正：很难转正，即使996也很难在6个月试用期后转正，周末不加班要被挂起来批评。早上弹性打卡，说9点30以前打卡就行，实际上要9点以前，否则这也是被优化的理由。目前我朋友部门2020年9月一起入职的一批人已经被集体优化了一半。
3、关于应届生：有网上人发帖说能链签了三方，发了offer也会毁约，需要注意。
PS：天眼查查询该公司的官司，基本都是劳动仲裁纠纷。

**Comment by vczh** [comment]
截图呢
