### ISSUE TITLE
知情人士爆尿: 那个说自己老公一毛钱股份没拿到还觉得他最牛逼的谁 我真是大写加粗的呵呵哒了

### ISSUE THREAD

**Issue by levy9527** [shengxinjing/programmer-job-blacklist#35]
[女作者前同事观点](https://mp.weixin.qq.com/s?__biz=MzU1OTAwODI2Mw==&mid=2247483661&idx=1&sn=cec78e805629298224c0dc4676648499&chksm=fc1c9e65cb6b1773b61d47a5c9a797355bcaf9488af58d40fec5b4d35646c140d83af8c43956&mpshare=1&scene=1&srcid=0223DDbFEafsW83yuxU9f4zn&key=aec670e58253e187b4838f3c5e0909c1e08012f05b23a93790eb938df4df9d2e9f63b41bab85c1aa5d004638ab519a8ef358d0a8138c46d1e27e773bbe5de5117ba1410e133335bc07d598cef560159a&ascene=0&uin=MzM3Mjc5Mzc1&devicetype=iMac+MacBookPro12%252C1+OSX+OSX+10.12.3+build(16D32)&version=12010310&nettype=WIFI&fontScale=100&pass_ticket=MW5IQlB1iH64SLXmCnNmd6ioX4KcN1FrHky0w73UXp2cT9MVoIUdhMGn57l4E5tF)

看过之后, 感觉想法就不一样了. 真相扑朔迷离, 建议把**自己老公最牛逼**那篇文章去掉吧

**Comment by shengxinjing** [comment]
@levy9527 看过之后并没有啥不一样，并没有就事论事

**Comment by shengxinjing** [comment]
不过我会把你的链接加上

**Comment by levy9527** [comment]
女作者看起来也没说实话, 这么说来, 两篇文章相当于狗咬狗, 不过是利益之争. 可能 `北京展程科技` 有做得不好的地方,  但她写的文章都是她一面之词, 她老公并没有站出来说话, 这女的为人不可信的话, 当然话也不能尽信啦.

**Comment by shengxinjing** [comment]
@levy9527 我把号称反转的链接也发出来了

**Comment by realpg** [comment]
@levy9527 
没看过内容 我就问您一句，您是男的吧，您老婆的同事能对您公司的鸡毛蒜皮小事儿信手拈来么……
我觉得看这个标题就特么知道是职业公关文

**Comment by levy9527** [comment]
@realpg 没看过就不要评论了吧 还有没事别at我了 我只是提出一个不同的观点 你可以不认同 我不想自己再陷入讨论的漩涡中
