### ISSUE TITLE
不一定是出了奇葩事件才曝光

### ISSUE THREAD

**Issue by fifman** [shengxinjing/programmer-job-blacklist#38]
建议增加匿名保护，让内部员工揭露公司现状、比如水平低下、管理混乱等吐槽的功能。

**Comment by shengxinjing** [comment]
额 我没想搞那么复杂。。。每个公司都有乱七八糟的吐槽点

**Comment by lilydjwg** [comment]
这里需要什么匿名保护？需要匿名的用户可以自己通过匿名网络注册个 GitHub 账号来参与讨论呀，GitHub 又不要手机号验证。真正不好做到匿名的是内容。揭露的东西能知道的人不会很多，各种细节和行文习惯什么的联合起来会比较容易判断是谁在说话，技术上也没什么办法。
