### ISSUE TITLE
浙江农商数字科技公司，违法延长试用期，克扣工资

### ISSUE THREAD

**Issue by sharpnow** [shengxinjing/programmer-job-blacklist#393]

**Comment by zhuyanxuan** [comment]
这有啥好发的，晕，考雅思吧，出国工作，现在都选这条路了。

**Comment by sharpnow** [comment]
> 这有啥好发的，晕，考雅思吧，出国工作，现在都选这条路了。

😅😅😅😅😅😅😅😅你就像个nt，搞清楚这个project 是干啥的，就你知道考雅思是吧，都让你懂完了。
