### ISSUE TITLE
被以前雇主看到怎么办？

### ISSUE THREAD

**Issue by AngryLi** [shengxinjing/programmer-job-blacklist#52]
虽说离职了，但是被以前雇主看到我提了pr岂不是很尴尬O(∩_∩)O~

**Comment by shengxinjing** [comment]
我开项目都不怕，pr怕啥，我以前雇主就是百度 有啥尴尬的

**Comment by AngryLi** [comment]
@shengxinjing 老哥，稳！开放个邮箱吧，提交pr风险太大啦。。。

**Comment by AngryLi** [comment]
@shengxinjing 开放个邮箱如何，私下交流，提交pr风险太大了。以后雇主看到也有不小风险，刺头。

**Comment by shengxinjing** [comment]
或者你发链接发出来。。

**Comment by shengxinjing** [comment]
怕当刺头的话，还是不要维护这个名单了，我把这个issuse关了就行

**Comment by AngryLi** [comment]
**老哥，稳！**

**Comment by longXboy** [comment]
@AngryLi 粥粥不虚，站起来刚～
