### ISSUE TITLE
哔哩哔哩 flv.js作者低薪离职事件

### ISSUE THREAD

**Issue by ATKghost** [shengxinjing/programmer-job-blacklist#55]
如何看待哔哩哔哩的 flv.js 作者月薪不到 5000 元？https://www.zhihu.com/question/53686737/answer/136121534

如何看待哔哩哔哩的开源 HTML5 播放器内核 flv.js?
https://www.zhihu.com/question/51997376

从各方言论中看出B站的HR人渣，剥削员工。

**Comment by SilverBut** [comment]
赞同。
摘录知乎中部分答案：

> 当事人觉得自己待遇不公，尝试过找hr，找上级解决这个问题，得到了十分令人气愤的答复。

> 但问题是，B站不喜欢给已经招进来的人加薪，这就很恶心了。

> 2015年11月13日，幻电七大奇迹之冬天比夏天热。寒冬腊月大家在办公室里穿短袖、吹电扇、开加湿器还是热的没法工作，行政不得不每天买冰块放在办公室里降温。一楼大堂时不时会出现B站员工成群结队穿着短袖啃着棒冰从一群穿着棉袄羽绒衣的其他公司员工旁边走过的神奇景象。后来B站似乎在大楼的中央空调之外自己又安装了一套空调，不知道今年的冬天会不会比去年好些。

陈睿回应：

> 所谓“HR因为他没有大学学历就不予加薪”是完全没有的事。

> 2. 6000元的入职工资是因为谦谦在2015年3月入职时没有工作经验，而且那时b站的薪资水平也明显低于现在。

> 如果b站的薪资体系真有问题，我们也不可能招募到200名技术人才。

**Comment by nshen** [comment]
这有点玻璃心了吧。。。又不是公司承诺做出来flv.js给加薪然后没加。。自己做开源项目成功了，觉得现在职位不合适了就跳槽呗。

**Comment by shengxinjing** [comment]
@nshen 赞同你的观点，这个只能算是B站不识货 仅此而已，B站并没有承诺了做不到，这点还是有目共睹的

**Comment by shengxinjing** [comment]
B站不识货，不愿意给谦谦加工资，谦谦就离职换工作 人之常情，并没有什么问题

**Comment by lurenok** [comment]
跟对一个老大也很重要

**Comment by lizeqiangd** [comment]
@nshen  嗯.又见面啦.   我之前和当事人是同事    问题没那么复杂..都是知乎上面说严重了

**Comment by nshen** [comment]
@lizeqiangd 真是同事么？怎么感觉你工资是当事人10倍以上呢 ( /) V (\ )
