### ISSUE TITLE
 58 赶集集团强制员工 996 加班

### ISSUE THREAD

**Issue by caoglishcn** [shengxinjing/programmer-job-blacklist#58]
如何看待 58 赶集集团强制员工 996 加班？
https://www.zhihu.com/question/50217184

**Comment by yy1300326388** [comment]
这是在强制让你走的感觉

**Comment by linbaiye** [comment]
这明摆着的，不是背后捅你黑刀。

**Comment by xiaochengxuyuan** [comment]
要是996的公司能上list，那感觉可以弄白名单了.....

**Comment by shengxinjing** [comment]
这个算有争议吧，毕竟这是明摆着的 没有阴你的感觉吧，虽然也很不爽
