### ISSUE TITLE
成都黑名单

### ISSUE THREAD

**Issue by JackTheMico** [shengxinjing/programmer-job-blacklist#59]
1 达内
2 国信安
3 火星时代
4 51testing{博为峰）
5 千峰
6 睿锋科技
7 华信智源
8 天纵科技
9 智游
10 多迪
11 盛课盟
12 华清远见
13 青麦
14 糖果时代
15 北京优创
16 蜗牛创 
17 源代码
18 怪狗
19 青鸟
20 博创华宇
21 鼎育
22 翡翠
23 尚学堂
24 米乐教育
25 完美动力
26 川软
27 中软国际
28 汇众教育
29 华育国际
30 川铭教育
31 闪客教育
32 华迪
33 成都力方 ...
34 北大青鸟
35 兔子师傅
36 鑫佳鑫科技
37 红糖科技
38 智汇蓝图
39 海德智和
40 智汇工场
41 华为高科
42 云知学
43 成都谢尔科技有限公司
44 华为高科(北京)软件有限公司
45 泸州掌宝合力科技有限公司
46 绵阳奇佳科技有限公司乐山分公司
47 泸州市博通科技开发有限公司
48 中软创新(北京)科技有限公司
49 成都中软卓越信息技术有限公司
50 北京中软国际教育科技有限公司成都分公司
51 广州碧软信息科技有限公司
52 成都博为峰软件技术有限公司
53 中软互联(北京)科技有限公司
54 荣新中关村IT人才服务中心
55 成都睿峰科技有限公司	
56 荣新中关村IT人才服务中心
57 广州多迪网络科技有限公司
58 中软国际有限公司
59 成都暮光时代科技有限公司
60 成都怪狗软件有限公司
61 成都尚学堂科技有限公司
62 成都麦子信息技术有限公司
63 成都糖果时代科技有限公司
64 四川狮子座互联网科技有限公司
65 四川红糖科技有限公司
66 旅烨网络科技成都分公司
67 达内科技有限公司
68 成都睿远商务信息咨询有限公司
69 成都令鹿科技有限公司

（不断更新，有更多的可以直接告诉群主）

                                        IT技术公司黑名单

1 成都诚品软件    拖欠工资
2 成都掌金科技    拖欠工资
3 成都九九数码    拖欠工资
4 成都易思博
5 成都B区掌游互动 专坑熟人
6 古威天地        拖欠工资
7 多享            面试题太多50道
8 泰和盈动        工资发不起
9 成都云动智联科技    老板太忽悠   说的福利，从来都是找借口不给，还要自己带电脑
10 成都瑞安云      拖工资
11 成都华格，成都人联科技，成都微政通，成都微企通(同一家公司)      拖欠工资
12 佳胜科技        老板太忽悠，急用人时狂招人，不用人时就开除，说的福利也木有

----------------------------------------------

13 网众天弘科技    公司制度过于规范：办公桌上除了电脑配套东西及笔记本一律不让放；离开座位椅子不端正罚款30，穿短裤、拖鞋、
	        裙子罚款100；必须转发微信推广，否则罚款200；看见老板不喊直接辞退；公司单休，节假日需听从安排去
	        派发传单，包括技术人员

----------------------------------------------

14 成都明驰科技有限公司 地址 清江东路 老板姓高 成都婚庆协会副会长  理由：老板太忽悠，急用人时狂招人，不用人时就开除，老板不懂技术，总是指指点点说什么架构，做个企业站需要毛线架构哇，有项目就招人 没项目就开除。

----------------------------------------------

15 航科智宇  卸磨杀驴，迟到1分钟扣10元，扣双倍，迟到半小时扣当天三倍工资，旷工一天扣3天工资，加班不算加班，单休。绩效无故乱扣，人事是个大水逼  招聘消息  90%加  什么六险一金  其实只有社保  迟到1分钟扣20  迟到3次扣工资的3%，承诺的事百分之90假，然后  离职申请上  原因人事逼着离职人员写  赶进度  不适应  不能写实情，人事给谈的工资里面  包括了30%的绩效  然而 每月绩效  扣几大百  就是 谈的工资  每月扣， 每晚加班到11点算早  一般的12点-1点，这样都不算加班  是赶进度

-------------------------------------------------
16 成都令鹿科技有限公司  ----拖欠工资3个月，很多员工因为没发工资辞职后就不要想拿到工资了；老板太忽悠。

17 成都西谷曙光数字技术有限公司 ----自从来了几个华为的高管就天天加班到9点10点，有时候周末也加班，而且没有加班费或调休，早上必须9点到！只有社保，没有住房公积金，没有项目提成，没有年终奖，请假就扣全天的钱！

**Comment by loatheb** [comment]
这也算黑名单....

> 7 多享 面试题太多50道

**Comment by acearth** [comment]
除非是50道选择或者填空题。。

**Comment by zinking** [comment]
黑名单里的每一条不都得知乎上扬扬洒洒的写上一篇，然后cross reference。 这种上来就列了50多家是不是太草率太鲁莽了。 然后这些公司是不是可能会改名什么的， 总之要考虑的方面还很多，bug也很多。

**Comment by nazhenhuiyi** [comment]
@JackTheMico 你为何这么吊

**Comment by nshen** [comment]
@JackTheMico 最后加一句，以上为亲身经历 。会显得你更吊

**Comment by JackTheMico** [comment]
群里大家一起总结的，第17个是亲身经历

**Comment by shengxinjing** [comment]
。。没有任何链接。。

**Comment by LJX1024** [comment]
我来补充一个。这家公司是变着名字招聘人，只知道公司地址： 成都市高新区理想中心一栋15楼1503。HR 不太负责，事先不根本看简历，我讲了大半天，突然说: " 你是来面试XX岗位的啊，我还以为XXX。”  顿时，就不太想面试了。还好，HR 最后也说我不太符合他们要求。

**Comment by flyerSon** [comment]
这么多？

**Comment by jide123456** [comment]
广州碧软信息科技有限公司  这个公司为什么不好，有老铁知道的么

**Comment by wrsz** [comment]
智慧式控股，拖欠工资，威胁员工，殴打员工而且上报，负面新闻很多。

**Comment by CTZFET** [comment]
成都蓉视通科技有限公司

**Comment by CTZFET** [comment]
shit尝一下

**Comment by supreme429** [comment]
我想提几个 可以吗

**Comment by kcersing** [comment]
必须可以
________________________________
发件人: supreme429 <notifications@github.com>
发送时间: 2019年8月14日 2:17
收件人: shengxinjing/programmer-job-blacklist <programmer-job-blacklist@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [shengxinjing/programmer-job-blacklist] 成都黑名单 (#59)


我想提几个 可以吗

―

**Comment by nightzjp** [comment]
一石数字技术成都有限公司，法人施国鹏；
入职四年，公司没有任何规章制度。工作安排都是微信；最近一次听了领导”卢荣新“的口头安排采购了一套产品，后期拒绝报销！
然后被欺骗写了离职申请(写了之后给你补偿，要走公司流程)；
社保最低，甚至多次忘记缴纳！公积金都是用员工的钱公司的名义购买！
领导”蓝志康“在员工离职之后背刺员工！

**Comment by zifengziyun** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
