### ISSUE TITLE
还有饿了么

### ISSUE THREAD

**Issue by himemeizhi** [shengxinjing/programmer-job-blacklist#61]
1、坑技术合伙人
https://www.zhihu.com/question/38295860/answer/76086628

2、黑作坊曝光事件
[黑作坊曝光事件](https://zh.wikipedia.org/wiki/饿了么#.E9.BB.91.E4.BD.9C.E5.9D.8A.E6.9B.9D.E5.85.89.E4.BA.8B.E4.BB.B6)

**Comment by skywind3000** [comment]
其实公司改个名字都是很简单的，特别中小企业
