### ISSUE TITLE
想问下commit readme为何被forbidden了

### ISSUE THREAD

**Issue by BeyondW** [shengxinjing/programmer-job-blacklist#64]
第一次用还不太会，求大大好心解答下

**Comment by AnyISalIn** [comment]
你要先 fork 本项目，然后提交更改到你更改到你 fork 的 repo，然后发个 pull request 到这个项目等待合并，可以看廖雪峰的教程， [`git 教程`](http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000)
