### ISSUE TITLE
成都前端群有成都培训公司和垃公司的黑名单

### ISSUE THREAD

**Issue by wuxinwei240** [shengxinjing/programmer-job-blacklist#69]
1 达内
2 国信安
3 火星时代
4 51testing{博为峰）
5 千峰
6 睿锋科技
7 华信智源
8 天纵科技
9 智游
10 多迪
11 盛课盟
12 华清远见
13 青麦
14 糖果时代
15 北京优创
16 蜗牛创 
17 成都令鹿科技有限公司
18 怪狗
19 青鸟
20 博创华宇
21 鼎育
22 翡翠
23 尚学堂
24 米乐教育
25 完美动力
26 川软
27 中软国际
28 汇众教育
29 华育国际
30 川铭教育
31 闪客教育
32 华迪
33 成都力方 ...
34 北大青鸟
35 兔子师傅
36 鑫佳鑫科技
37 红糖科技
38 智汇蓝图
39 海德智和
40 智汇工场
41 华为高科
42 云知学
43 成都谢尔科技有限公司
44 华为高科(北京)软件有限公司
45 泸州掌宝合力科技有限公司
46 绵阳奇佳科技有限公司乐山分公司
47 泸州市博通科技开发有限公司
48 中软创新(北京)科技有限公司
49 成都中软卓越信息技术有限公司
50 北京中软国际教育科技有限公司成都分公司
51 广州碧软信息科技有限公司
52 成都博为峰软件技术有限公司
53 中软互联(北京)科技有限公司
54 荣新中关村IT人才服务中心
55 成都睿峰科技有限公司	
56 荣新中关村IT人才服务中心
57 广州多迪网络科技有限公司
58 中软国际有限公司
59 成都暮光时代科技有限公司
60 成都怪狗软件有限公司
61 成都尚学堂科技有限公司
62 成都麦子信息技术有限公司
63 成都糖果时代科技有限公司
64 四川狮子座互联网科技有限公司
65 四川红糖科技有限公司
66 旅烨网络科技成都分公司
67 达内科技有限公司
68 成都睿远商务信息咨询有限公司
69 成都令鹿科技有限公司

（不断更新，有更多的可以直接告诉群主）

                                        IT技术公司黑名单

1 成都诚品软件    拖欠工资
2 成都掌金科技    拖欠工资
3 成都九九数码    拖欠工资
4 成都易思博
5 成都B区掌游互动 专坑熟人
6 古威天地        拖欠工资
7 多享            面试题太多50道
8 泰和盈动        工资发不起
9 成都云动智联科技    老板太忽悠,说的福利，从来都是找借口不给，还要自己带电脑
10 成都瑞安云      拖工资
11 成都华格，成都人联科技，成都微政通，成都微企通(同一家公司)      拖欠工资
12 佳胜科技        老板太忽悠，急用人时狂招人，不用人时就开除，说的福利也木有

----------------------------------------------

13 网众天弘科技    公司制度过于规范：办公桌上除了电脑配套东西及笔记本一律不让放；离开座位椅子不端正罚款30，穿短裤、拖鞋、裙子罚款100；必须转发微信推广，否则罚款200；看见老板不喊直接辞退；公司单休，节假日需听从安排去派发传单，包括技术人员

----------------------------------------------

14 成都明驰科技有限公司 地址 清江东路 老板姓高 成都婚庆协会副会长  理由：老板太忽悠，急用人时狂招人，不用人时就开除，老板不懂技术，总是指指点点说什么架构，做个企业站需要毛线架构哇，有项目就招人 没项目就开除。

----------------------------------------------

15 航科智宇  卸磨杀驴，迟到1分钟扣10元，扣双倍，迟到半小时扣当天三倍工资，旷工一天扣3天工资，加班不算加班，单休。绩效无故乱扣，人事是个大水逼  招聘消息  90%加  什么六险一金  其实只有社保  迟到1分钟扣20  迟到3次扣工资的3%，承诺的事百分之90假，然后  离职申请上  原因人事逼着离职人员写  赶进度  不适应  不能写实情，人事给谈的工资里面  包括了30%的绩效  然而 每月绩效  扣几大百  就是 谈的工资  每月扣， 每晚加班到11点算早  一般的12点-1点，这样都不算加班  是赶进度

-------------------------------------------------

16 成都令鹿科技有限公司  ----拖欠工资3个月，很多员工因为没发工资辞职后就不要想拿不到工资了；老板太忽悠。

-------------------------------------------------

17 成都欧特电子有限公司，发不起工资

18 成都启超网络科技有限公司 拖欠工资,不是技术导向型公司,外包公司,还有加分公司在绵阳:叫绵阳启超网络科技有限公司

19 成都极感科技，招了新员工，三个月，就把人辞退了，老板是川大老师，公司全部是研究生，一个月500,外面招来的，一般不转正，项目需求的话，就会转正，但是，我和另外一个师兄转正后，今天被辞退了，说是公司资金周转不开，但是上礼拜我们刚刚集体帮助公司通过了cmmi 认证，昨天宣布认证通过，国庆过后研一新生就来了，项目也不紧张，我们三个外面招来的人就被辞了，一个写需求文档妹儿和前端，他们也不缺人，有研究生被捏在手里的，他们要拿毕业证，只是我们的人，不要上当了。
   --- 更新时间 2016.09.30 23:00 ---  

20 成都云聚互动 的周朝江老板！拖欠工资、拖欠社保不交、需求无厘头、6个月没发过工资，开除测试，开除产品经理，人事都走了，还好意思说人家自己走，明明就是被开除，让会计去做运营，关键是开了人还没给一分钱。
   20资源来自网络, 	详请链接: http://mycd.qq.com/t-24184408-1.htm    --- 更新时间 2016.09.30 23:00 --- 
 
21 索引国际教育,拖欠工资（我七月份离职的。现在还有一个月工资没发），地址在在中航城市广场 。--- 更新时间 2016.09.30 23:11 ---
 
22 成都好房通科技股份有限公司 (一家极其恶心的公司) http://bbs.tianya.cn/post-763-875937-1.shtml

   -----------------   大家有资源都可以更新上去哈，我加进去的这几条信息，我都会针对来源做详细记录，大家也可以哈   --------------

**Comment by 2shui** [comment]
[http://www.itblacklist.cn/](http://www.itblacklist.cn/)  IT黑名单

**Comment by AngryLi** [comment]
我就想说 程序员 是不是应该也有个黑名单，坐吃等死的程序员都写上去，不能只让企业吃亏是不是。

**Comment by 2efPer** [comment]
楼上，企业当然不吃亏，各个企业HR内部一般都分享黑名单，而且有背景调查的公司啊
