### ISSUE TITLE
上一家公司没钱发工资还招聘我进去

### ISSUE THREAD

**Issue by liangyuanpeng** [shengxinjing/programmer-job-blacklist#93]
发现拖欠了三个月工资，做了一个礼拜立刻跑了

**Comment by long1112** [comment]
说出那家公司的名字:-)



Yan Long
 
发件人： liangyuanpeng
发送时间： 2017-05-22 17:27
收件人： shengxinjing/programmer-job-blacklist
抄送： Subscribed
主题： [shengxinjing/programmer-job-blacklist] 上一家公司没钱发工资还招聘我进去 (#93)
发现拖欠了三个月工资，做了一个礼拜立刻跑了

**Comment by Liangxiujun** [comment]
劳动仲裁，告他

**Comment by shengxinjing** [comment]
没有公司名字，只能关了
