### ISSUE TITLE
广州聆歌信息科技有限公司

### ISSUE THREAD

**Issue by David-Pan** [shengxinjing/programmer-job-blacklist#95]
老板陈志国拖欠工资
广州市越秀区先烈中路

**Comment by powerkom** [comment]
这名员工突然辞职，不肯进行交接，并且上了不足半个月班，因为没有满足他发放一个工资的要求就在大放厥词。公司从实习生培养他成长，因为一己之私就诋毁公司，诋毁老板，这种员工我相信到那个公司都不会受欢迎。
