### ISSUE TITLE
北京长瑞时代

### ISSUE THREAD

**Issue by XiaochenCui** [shengxinjing/programmer-job-blacklist#96]
- 工资低
- 老板不懂技术，而且老板直接指挥每个员工
- 项目一团乱码，版本控制都没有
- python 代码中居然能夹杂中文变量，老板还舔着脸说能跑起来就行，简直是人间奇闻

**Comment by XiaochenCui** [comment]
工资拖欠不拖欠我不清楚，因为干了三天就跑路了

**Comment by shengxinjing** [comment]
这个不算坑程序员把

**Comment by szoyj** [comment]
应该是干易语言出生吧

2017-06-08 11:09 GMT+08:00 woniuppp <notifications@github.com>:
